[package]
name = "uzumibi-cloudflare-ext"
version = "0.4.1"
edition = "2024"
authors = ["Uchio Kondo <udzura@udzura.jp>"]
description = "Cloudflare Workers extension for Uzumibi (mruby/edge serverless framework)"
license = "BSD-3-Clause"

[dependencies]
mrubyedge = { version = "2.1.0", features = [
    "no-wasi",
], default-features = false }
uzumibi-gem = "0.6.1"
mrubyedge-serde-json = "0.3.0"
serde_json = "1"

[features]
default = []
enable-external = []
queue = ["enable-external"]
